stages:
  - init
  - run
  - finish

.base:
  variables:
    ARCHES: "x86_64"
    TYPES: "qcow2"
    FEDORA_VERSION: "43"
    EL9_VERSION: "9.7"
    EL10_VERSION: "10.1"
    FROM_REFS: |-
      quay.io/fedora/fedora-bootc:${FEDORA_VERSION}
      quay.io/centos-bootc/centos-bootc:stream10
      quay.io/centos-bootc/centos-bootc:stream9
      registry.redhat.io/rhel9/rhel-bootc:${EL9_VERSION}
      registry.redhat.io/rhel10/rhel-bootc:${EL10_VERSION}

.terraform:
  extends: .base
  tags:
    - terraform

init:
  extends: .base
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - |
      for FROM_REF in $FROM_REFS; do
        schutzbot/update_github_status.sh start "$FROM_REF"
      done

# run:
#   extends: .terraform
#   stage: run
#   parallel:
#     matrix:
#       - FROM_REF: "quay.io/fedora/fedora-bootc:${FEDORA_VERSION}"
#         CONTAINERFILE: "fedora"
#         RUNNER: "aws/centos-stream-10-x86_64"
#         FROM_CREDS: ""
#         DST_REF: "quay.io/osbuild/fedora-bootc:${FEDORA_VERSION}"
#         DST_CREDS: "$QUAY_CREDS"

#       - FROM_REF: "registry.redhat.io/rhel9/rhel-bootc:${EL9_VERSION}"
#         CONTAINERFILE: "el9"
#         RUNNER: "aws/rhel-10.1-ga-x86_64"
#         FROM_CREDS: "$RH_CREDS"
#         DST_REF: ""
#         DST_CREDS: ""

#       - FROM_REF: "quay.io/centos-bootc/centos-bootc:stream10"
#         CONTAINERFILE: "el10"
#         RUNNER: "aws/centos-stream-10-x86_64"
#         FROM_CREDS: ""
#         DST_REF: "quay.io/osbuild/centos-bootc:stream10"
#         DST_CREDS: "$QUAY_CREDS"

#       - FROM_REF: "quay.io/centos-bootc/centos-bootc:stream9"
#         CONTAINERFILE: "el9"
#         RUNNER: "aws/centos-stream-10-x86_64"
#         FROM_CREDS: ""
#         DST_REF: "quay.io/osbuild/centos-bootc:stream9"
#         DST_CREDS: "$QUAY_CREDS"

#       - FROM_REF: "registry.redhat.io/rhel10/rhel-bootc:${EL10_VERSION}"
#         CONTAINERFILE: "el10"
#         RUNNER: "aws/rhel-10.1-ga-x86_64"
#         FROM_CREDS: "$RH_CREDS"
#         DST_REF: ""
#         DST_CREDS: ""

#   before_script:
#     - . schutzbot/gitlab-utils.sh
#     - section_start before_script "Run before script section"
#     - schutzbot/ec2-spot-check.sh &
#     - mkdir -p /tmp/artifacts && schutzbot/ci_details.sh > /tmp/artifacts/ci-details-before-run.txt
#     - cat schutzbot/team_ssh_keys.txt | tee -a ~/.ssh/authorized_keys > /dev/null
#     - sudo dnf -y install buildah
#     - |
#       # Push only on main branch
#       if [ "$CI_COMMIT_BRANCH" != "main" ]; then
#         unset DST_CREDS
#       fi
#     - section_end before_script
#   script:
#     - schutzbot/build.sh
#   after_script:
#     - . schutzbot/gitlab-utils.sh
#     - section_start after_script "Run after script section"
#     - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-after-run.txt || true
#     - schutzbot/unregister.sh || true
#     - schutzbot/update_github_status.sh update "$FROM_REF" || true
#     - schutzbot/save_journal.sh || true
#     - schutzbot/upload_artifacts.sh
#     - if [ "$CI_JOB_STATUS" = "success" ]; then schutzbot/update_github_status.sh finish "$FROM_REF"; fi
#     - section_end after_script


test:
  extends: .terraform
  stage: run
  variables:
    RUNNER: aws/rhel-10.1-ga-x86_64
  before_script:
    - . schutzbot/gitlab-utils.sh
    - section_start before_script "Run before script section"
    - schutzbot/ec2-spot-check.sh &
    - mkdir -p /tmp/artifacts && schutzbot/ci_details.sh > /tmp/artifacts/ci-details-before-run.txt
    - cat schutzbot/team_ssh_keys.txt | tee -a ~/.ssh/authorized_keys > /dev/null
    - section_end before_script
  script:
    - podman run $(podman build -f distribution/Dockerfile-ubi . | tail -n 1) --repo placeholder.org
  after_script:
    - . schutzbot/gitlab-utils.sh
    - section_start after_script "Run after script section"
    - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-after-run.txt || true
    - schutzbot/unregister.sh || true
    - schutzbot/save_journal.sh || true
    - schutzbot/upload_artifacts.sh
    - if [ "$CI_JOB_STATUS" = "success" ]; then schutzbot/update_github_status.sh finish; else schutzbot/update_github_status.sh update; fi
    - section_end after_script


finish:
  extends: .base
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - |
      for FROM_REF in $FROM_REFS; do
        schutzbot/update_github_status.sh finish "$FROM_REF"
      done
