stages:
  - init
  - run
  - finish

.base:
  variables:
    DISTROS: |-
      centos-9
      centos-10
      rhel-9.7
      rhel-10.1

.terraform:
  extends: .base
  tags:
    - terraform

init:
  extends: .base
  stage: init
  interruptible: true
  tags:
    - shell
  script:
    - |
      for DISTRO in $DISTROS; do
        schutzbot/update_github_status.sh start "$DISTRO"
      done

run:
  extends: .terraform
  stage: run
  variables:
    RUNNER: aws/rhel-10.1-ga-x86_64
  parallel:
    matrix:
      - DISTRO: "centos-9"
      - DISTRO: "centos-10"
      - DISTRO: "rhel-9.7"
      - DISTRO: "rhel-10.1"

  before_script:
    - . schutzbot/gitlab-utils.sh
    - section_start before_script "Run before script section"
    - schutzbot/ec2-spot-check.sh &
    - mkdir -p /tmp/artifacts && schutzbot/ci_details.sh > /tmp/artifacts/ci-details-before-run.txt
    - cat schutzbot/team_ssh_keys.txt | tee -a ~/.ssh/authorized_keys > /dev/null
    - sudo dnf -y install buildah
    - |
      # Push only on main branch
      if [ "$CI_COMMIT_BRANCH" != "main" ]; then
        unset DST_CREDS
      fi
    - section_end before_script
  script:
    - schutzbot/container-build.sh $DISTRO
  after_script:
    - . schutzbot/gitlab-utils.sh
    - section_start after_script "Run after script section"
    - schutzbot/ci_details.sh > /tmp/artifacts/ci-details-after-run.txt || true
    - schutzbot/unregister.sh || true
    - schutzbot/update_github_status.sh update "$DISTRO" || true
    - schutzbot/save_journal.sh || true
    - schutzbot/upload_artifacts.sh
    - if [ "$CI_JOB_STATUS" = "success" ]; then schutzbot/update_github_status.sh finish "$DISTRO"; fi
    - section_end after_script

finish:
  extends: .base
  stage: finish
  dependencies: []
  tags:
    - shell
  script:
    - |
      for FROM_REF in $FROM_REFS; do
        schutzbot/update_github_status.sh finish "$FROM_REF"
      done
