images:
  - id: fedora
    containerfile: fedora
    pipeline: github
    from_image: quay.io/fedora/fedora-bootc
    from_tag: "43"
    to_image: quay.io/osbuild/fedora-bootc
    to_tag_prefix: "43"
    arches: [x86_64, aarch64]
    types: [qcow2, ec2, azure, gce]

  - id: el9
    containerfile: el9
    pipeline: github
    from_image: quay.io/centos-bootc/centos-bootc
    from_tag: stream9
    to_image: quay.io/osbuild/centos-bootc
    to_tag_prefix: stream9
    arches: [x86_64, aarch64]
    types: [qcow2, ec2, azure, gce]

  - id: el10
    containerfile: el10
    pipeline: github
    from_image: quay.io/centos-bootc/centos-bootc
    from_tag: stream10
    to_image: quay.io/osbuild/centos-bootc
    to_tag_prefix: stream10
    arches: [x86_64, aarch64]
    types: [qcow2, ec2, azure, gce]

  - id: rhel9
    containerfile: el9
    pipeline: shell
    from_image: registry.redhat.io/rhel9/rhel-bootc
    from_tag: 9.7
    arches: [x86_64]
    types: [qcow2]

  - id: rhel10
    containerfile: el10
    pipeline: shell
    from_image: registry.redhat.io/rhel10/rhel-bootc
    from_tag: 10.1
    arches: [x86_64]
    types: [qcow2]
