# Containerfile for {{ distro }}-{{ version }} {{ image_type }}
FROM {{ base_image }}

ARG TARGETARCH
ARG CONTAINERFILE

RUN dnf install -y --skip-unavailable \
    "@cloud-server-environment" \
    "btrfs-progs" \
    "glibc-langpack-en" \
    "python3-dnf-plugin-tracer" \
{% if image_type == "ec2" %}
    "amazon-ec2-utils" \
    "awscli2" \
    "ec2-instance-connect" \
{% endif %}
{% if image_type == "azure" %}
    "WALinuxAgent" \
    "azure-vm-utils" \
    "hyperv-daemons" \
    "kernel-modules" \
{% endif %}
{% if image_type == "gce" %}
    "google-compute-engine-guest-configs" \
    "google-compute-engine-oslogin" \
    "google-guest-agent" \
{%- endif %}
{% if image_type == "qcow2" %}
    "qemu-guest-agent" \
{% endif %}
{%- if image_type == "gce" %} \
    --exclude="cloud-init" \
{% endif %}
    --exclude="dracut-config-rescue" \
    --exclude="firewalld" \
    --exclude="fwupd" \
    --exclude="geolite2-city" \
    --exclude="geolite2-country" \
    --exclude="plymouth" \
    --exclude="*-firmware" && \
    dnf clean all && \
    rm -rf /var/cache/dnf

RUN echo -e 'kargs = ["no_timer-check"]\nmatch-architectures = ["x86_64"]' > /usr/lib/bootc/kargs.d/50-no-timer-check.toml && \
    echo 'kargs = ["systemd.firstboot=off"]' > /usr/lib/bootc/kargs.d/50-systemd-firstboot.toml && \
    echo -e 'kargs = ["console=tty1 console=ttyS0,115200n8"]\nmatch-architectures = ["x86_64"]' > /usr/lib/bootc/kargs.d/50-console.toml
{% if image_type in ("ec2", "azure", "qcow2") %}

RUN systemctl enable \
{% if version|ge("43") %}
    "cloud-init-network.service" \
{% else %}
    "cloud-init.service" \
{% endif %}
    "cloud-config.service" \
    "cloud-init-local.service" \
    "cloud-final.service"
{% endif %}

COPY $CONTAINERFILE /root/Containerfile
