FROM registry.redhat.io/ubi10/buildah:latest

USER root
RUN dnf install -y \
    python3 \
    python3-pyyaml \
    make \
    skopeo \
    subscription-manager \
    git \
    awscli2 \
    && dnf clean all \
    && rm -rf /var/cache/dnf

WORKDIR /workspace
COPY . /workspace

RUN make matrix

ENTRYPOINT ["/workspace/entrypoint.sh"]
