FROM registry.redhat.io/ubi10/ubi:10

RUN dnf install -y \
    python3 \
    python3-pip \
    buildah \
    subscription-manager \
    git \
    && dnf clean all \
    && rm -rf /var/cache/dnf

WORKDIR /workspace
COPY . /workspace
