FROM registry.access.redhat.com/ubi10/ubi-minimal:latest

RUN microdnf install -y buildah python3

RUN mkdir /containerfiles
COPY ./containerfiles/Containerfile* /containerfiles/

# rely on CI scripts for now
COPY ./schutzbot /schutzbot

COPY ./distribution/entrypoint.py /opt/entrypoint.py
COPY ./distribution/temp-entrypoint.sh /opt/entrypoint.sh
ENTRYPOINT ["/opt/entrypoint.sh"]
