apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: bootc-foundry-containers
  annotations:
    openshift.io/display-name: Bootc-foundry containers cronjob
    description: |
      Cronjob which rebuilds the derived bootc containers.
    tags: golang
    iconClass: icon-shadowman
    template.openshift.io/provider-display-name: Red Hat, Inc.
labels:
  template: bootc-foundry-containers
objects:
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      labels:
        service: image-builder
      name: bootc-foundry-containers
    spec:
      # every 20 minutes
      schedule: "*/20 * * * *"
      concurrencyPolicy: Forbid
      # don't run if the job doesn't get scheduled within 30 minutes
      startingDeadlineSeconds: 1800
      jobTemplate:
        spec:
          template:
            spec:
              serviceAccountName: bootc-foundry
              restartPolicy: Never
              containers:
                - image: "${IMAGE_NAME}:${IMAGE_TAG}"
                  name: bootc-foundry
                  args:
                    - "--repo"
                    - "${REPO}"
                  volumeMounts:
                    - name: tmp
                      mountPath: /tmp
                  resources:
                    requests:
                      cpu: "${CPU_REQUEST}"
                      memory: "${MEMORY_REQUEST}"
                    limits:
                      cpu: "${CPU_LIMIT}"
                      memory: "${MEMORY_LIMIT}"
              volumes:
                - name: tmp
                  emptyDir: {}

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: bootc-foundry
    imagePullSecrets:
      - name: quay.io

parameters:
  - description: maintenance image name
    name: IMAGE_NAME
    value: quay.io/redhat-services-prod/insights-management-tenant/image-builder-bootc-foundry/bootc-foundry
    required: true
  - description: composer image tag
    name: IMAGE_TAG
    required: true
  - name: CPU_REQUEST
    description: CPU request per container
    value: "50m"
  - name: CPU_LIMIT
    description: CPU limit per container
    value: "100m"
  - name: MEMORY_REQUEST
    description: Memory request per container
    value: "128Mi"
  - name: MEMORY_LIMIT
    description: Memory limit per container
    value: "512Mi"
  - name: REPO
    description: repo to push to
    value: "placeholder.org"
