name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lint dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install -y shellcheck yamllint

      - name: Lint
        run: make lint
